name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-and-release
  cancel-in-progress: false

jobs:

  build-and-release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
           ref: v1.0.0

      - name: Build Unity project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Star-Wars-Combat-Arena
          targetPlatform: StandaloneWindows64
          buildsPath: build

      - name: Upload Unity build
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Build
          path: build/


