name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-and-release
  cancel-in-progress: false

jobs:

  build-and-release:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
           ref: v1.0.0

      - name: Get Unity version
        id: unity-version
        shell: bash
        run: |
          UNITY_VERSION=$(grep 'm_EditorVersion:' Star-Wars-Combat-Arena/ProjectSettings/ProjectVersion.txt | cut -d ' ' -f2)
          echo "Unity version: $UNITY_VERSION"
          echo "version=$UNITY_VERSION" >> "$GITHUB_OUTPUT"

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
           path: Star-Wars-Combat-Arena/Library
           key: UnityLibrary-${{ runner.os }}-${{ steps.unity-version.outputs.version }}-${{ hashFiles('Star-Wars-Combat-Arena/Packages/packages-lock.json', 'Star-Wars-Combat-Arena/ProjectSettings/ProjectVersion.txt') }}
           restore-keys: |
             UnityLibrary-${{ runner.os }}-${{ steps.unity-version.outputs.version }}-


      - name: Build Unity project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Star-Wars-Combat-Arena
          targetPlatform: StandaloneWindows64
          buildsPath: build

      - name: Upload Unity build
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Build
          path: build/


