name: Create Release Tag

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  create-tag:
    # Run the job only if the PR request was truly merged
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: latest
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)

          if [ -z "$latest_tag" ]; then
            echo "No previous tag found."
            echo "version=0.0.0" >> "$GITHUB_OUTPUT"
          else
            echo "Latest tag: $latest_tag"
            echo "version=${latest_tag#v}" >> "$GITHUB_OUTPUT"
          fi

      - name: Calculate next version
        id: version
        env:
          CURRENT_VERSION: ${{ steps.latest.outputs.version }}
          LABELS_JSON: ${{ toJSON(github.event.pull_request.labels.*.name) }}
        run: |
          # First release
          if [ "$CURRENT_VERSION" = "0.0.0" ]; then
            NEW_VERSION="1.0.0"

          # major release that breaks existing behavior
          elif echo "$LABELS_JSON" | jq -e 'index("breaking-change")' >/dev/null; then
            IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
            NEW_VERSION="$((major + 1)).0.0"

          # minor release that implements a new feature or improvement
          elif echo "$LABELS_JSON" | jq -e 'index("enhancement")' >/dev/null; then
            IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"

            if [ "$minor" -eq 9 ]; then
              NEW_VERSION="$((major + 1)).0.0"
            else
              NEW_VERSION="$major.$((minor + 1)).0"
            fi

          # patch release that fixes a bug
          elif echo "$LABELS_JSON" | jq -e 'index("bug")' >/dev/null; then
            IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
            NEW_VERSION="$major.$minor.$((patch + 1))"

          else
            echo "ERROR: PR has no version label."
            exit 1
          fi

          echo "New version: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Create and push tag
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          git tag "v$VERSION"
          git push origin "v$VERSION"
